# Generated by Django 5.0 on 2023-12-19 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conection', '0003_alter_ticketcase_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcase',
            name='user',
        ),
    ]
