# Generated by Django 5.0 on 2023-12-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conection', '0004_remove_ticketcase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcase',
            name='ticket_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
